---
title: Fst density in hybrid poplars
author: YOUR_NAME
date: 07/27/2021
output: html_document
---

## 1. Create a Fst density plot

- Import libraries and data
```{r}
library(ggplot2)
library(reshape2)

sig.fst <- read.table("~/Dropbox/Github/soc2021/week10/data/sig.fst", header=F)

neu.fst <- read.table("~/Dropbox/Github/soc2021/week10/data/neu.fst", header=F)

```


- Format and merge data

```{r}
sig <- data.frame(x=sig.fst$V2, label=rep('Significant (1764 SNPs)', 1764))

neu <- data.frame(x=neu.fst$V2, label=rep('Neutral (1912 SNPs)', 1912))

fst <- rbind(sig, neu)

```

- Make density plot

```{r}
ggplot(fst, aes(x, y=..density.., fill=label)) + xlim(0,1) +
  geom_density(color='black', alpha=0.7) +
  scale_fill_manual(values=c('orange', 'lightgray')) +
  labs(x=expression(paste("Admixture Zone"~italic(F)[ST])), y="Density (loci)",
      title=expression(paste("(b) "~italic(F)[ST]~" in "~italic("P. angustifolia")~" derived alleles"))) +
  theme(legend.position=c(0.8,0.9), legend.title=element_blank())

ggsave("
```


## 2. Reproducibility of results

- Read the data set

```{r}

pct <- read.table("~/Dropbox/Github/soc2021/week10/data/pval_counts.txt", header=T)

```

- Assign colors to numbers

```{r}
pct$fill <- ifelse(pct$counts_pvalzero == 0, "lightgray", 
              ifelse(pct$counts_pvalzero == 100, "orange", "black"))

```

- Draw a histogram to show reproducibility

```{r}
ggplot(pct, aes(counts_pvalzero, fill=fill)) +
  geom_histogram(binwidth=1) +
  scale_fill_manual(values=c("black", "gray", "orange"),
      labels=c("Variably Sig. (3847 SNPs)", "Never Sig. (1912 SNPs)", "Always Sig. (1764 SNPs)")) +
      labs(x="Num. of Introgress Replicates", y="Significantly introgressed loci",
           title="(a) Reproducibility of introgress results") +
  theme(legend.position=c(0.8,0.9), legend.title=element_blank(), legend.text=element_text(size=8))

```


## 3. Combine figures into a single panel


```{r, out.width=c('50%', '50%'), fig.show='hold'}
library(ggpubr)
library(ggplot2)
library(reshape2)

histplot <- ggplot(pct, aes(counts_pvalzero, fill=fill)) +
  geom_histogram(binwidth=1) +
  scale_fill_manual(values=c("black", "gray", "orange"),
      labels=c("Variably Sig. (3847 SNPs)", "Never Sig. (1912 SNPs)", "Always Sig. (1764 SNPs)")) +
      labs(x="Num. of Introgress Replicates", y="Significantly introgressed loci",
           title="(a) Reproducibility of introgress results") +
  theme(legend.position=c(0.8,0.9), legend.title=element_blank(), legend.text=element_text(size=8))


densityplot <- ggplot(fst, aes(x, y=..density.., fill=label)) + xlim(0,1) +
  geom_density(color='black', alpha=0.7) +
  scale_fill_manual(values=c('orange', 'lightgray')) +
  labs(x=expression(paste("Admixture Zone"~italic(F)[ST])), y="Density (loci)",
      title=expression(paste("(b) "~italic(F)[ST]~" in "~italic("P. angustifolia")~" derived alleles"))) +
  theme(legend.position=c(0.8,0.9), legend.title=element_blank())

print(histplot)

print(densityplot)




```




